server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: Autenticacion

adapters:
  r2dbc:
    host: ${R2DBC_HOST:postgres}
    port: ${R2DBC_PORT:5432}
    database: ${R2DBC_DATABASE:credi_ya}
    schema: ${R2DBC_SCHEMA:public}
    username: ${R2DBC_USERNAME:credi_user}
    password: ${R2DBC_PASSWORD:user}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}

security:
  jwt:
    secret: ${SPRING_SECURITY_JWT_SECRET:0Dz2RFrDttxXG9ZgQ9s6nJ8lcnFv9HQ1mFtuG3B0TXQ=}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}  # 1 hora
